import type { AppState } from "./types";

export const initialState: AppState = {
  bankrollName: "Banca principal",
  currency: "BRL",
  startingBalance: 13264.2,
  riskSettings: {
    unitPercent: 1,
    maxStakeUnits: 2,
    maxOpenExposurePercent: 5,
    lossStreakLimit: 2,
  },
  bookmakers: [
    { id: "bet365", name: "Bet365", balance: 6420.8, status: "synced", lastSyncLabel: "ha 2 min" },
    { id: "betano", name: "Betano", balance: 4820, status: "synced", lastSyncLabel: "ha 5 min" },
    { id: "sportingbet", name: "Sportingbet", balance: 1890.6, status: "manual", lastSyncLabel: "manual" },
    { id: "kto", name: "KTO", balance: 1251, status: "reconnect", lastSyncLabel: "reconectar" },
  ],
  strategies: [
    {
      id: "over-europa",
      name: "Over 1.5 ligas europeias",
      description: "Pre-live, odds 1.40 a 1.70 em ligas europeias",
      status: "active",
    },
    {
      id: "tenis-atp",
      name: "Tenis favorito ATP",
      description: "Entradas live em favoritos ATP com leitura de momentum",
      status: "active",
    },
    {
      id: "ncaa-live",
      name: "NCAA basquete ao vivo",
      description: "Live em basquete universitario",
      status: "paused",
    },
  ],
  bets: [
    {
      id: "bet-001",
      placedAt: "2026-05-06T11:15:00-03:00",
      eventAt: "2026-05-06T16:00:00-03:00",
      sport: "Futebol",
      league: "UCL",
      eventName: "Real Madrid x Manchester City",
      market: "Total de gols",
      selection: "Over 2.5 gols",
      bookmakerId: "bet365",
      strategyId: "over-europa",
      tags: ["euro", "overgols", "prelive"],
      stake: 250,
      odds: 1.92,
      status: "pending",
      closingOdds: 1.83,
      mode: "prelive",
    },
    {
      id: "bet-002",
      placedAt: "2026-05-06T12:20:00-03:00",
      eventAt: "2026-05-06T14:30:00-03:00",
      sport: "Tenis",
      league: "ATP Madri",
      eventName: "Alcaraz x Sinner",
      market: "Vencedor",
      selection: "Sinner",
      bookmakerId: "betano",
      strategyId: "tenis-atp",
      tags: ["tenis", "atp"],
      stake: 120,
      odds: 2.1,
      status: "won",
      payout: 252,
      closingOdds: 2.06,
      mode: "live",
    },
    {
      id: "bet-003",
      placedAt: "2026-05-05T18:40:00-03:00",
      eventAt: "2026-05-05T21:30:00-03:00",
      sport: "Futebol",
      league: "Brasileirao",
      eventName: "Palmeiras x Fluminense",
      market: "Ambos marcam",
      selection: "Sim",
      bookmakerId: "kto",
      tags: ["brasileirao"],
      stake: 200,
      odds: 1.78,
      status: "lost",
      payout: 0,
      closingOdds: 1.81,
      mode: "prelive",
    },
    {
      id: "bet-004",
      placedAt: "2026-05-05T22:10:00-03:00",
      eventAt: "2026-05-05T23:00:00-03:00",
      sport: "Basquete",
      league: "NBA",
      eventName: "Lakers x Celtics",
      market: "Spread",
      selection: "Lakers +5.5",
      bookmakerId: "bet365",
      tags: ["nba", "spread"],
      stake: 180,
      odds: 1.91,
      status: "cashout",
      payout: 276.4,
      closingOdds: 1.87,
      mode: "live",
    },
    {
      id: "bet-005",
      placedAt: "2026-05-04T15:55:00-03:00",
      eventAt: "2026-05-04T17:00:00-03:00",
      sport: "Futebol",
      league: "EPL",
      eventName: "Liverpool x Arsenal",
      market: "Resultado final",
      selection: "Liverpool",
      bookmakerId: "betano",
      strategyId: "over-europa",
      tags: ["premier"],
      stake: 300,
      odds: 1.85,
      status: "won",
      payout: 555,
      closingOdds: 1.82,
      mode: "prelive",
    },
  ],
  transactions: [
    {
      id: "tx-001",
      date: "2026-05-05T10:00:00-03:00",
      type: "deposit",
      bookmakerId: "bet365",
      description: "PIX",
      amount: 500,
    },
    {
      id: "tx-002",
      date: "2026-05-03T18:00:00-03:00",
      type: "withdrawal",
      bookmakerId: "betano",
      description: "PIX",
      amount: -800,
    },
  ],
};
